In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [1]:

srs1 = Series([1,2,3,4])

print(f"""
series : srs1
values : {srs1.values}
index : {srs1.index}
srs1[0] : {srs1[0]}
""")

srs2 = Series([1,2,3,4,5], index=['a','b','c','d','e'])

print(f"""
series : srs2
values : {srs2.values}
index : {srs2.index}
srs2['a'] : {srs2['a']}
""")




series : srs1
values : [1 2 3 4]
index : RangeIndex(start=0, stop=4, step=1)
srs1[0] : 1


series : srs2
values : [1 2 3 4 5]
index : Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
srs2['a'] : 1



Rank                      Team      GP   Won   Lost   Tied   Pct.   \
0      1           Dallas Cowboys     898    512    380      6  0.573   
1      2            Chicago Bears   1,386    761    583     42  0.564   
2      3        Green Bay Packers   1,352    743    571     38  0.564   
3      4  New England Patriots[b]     900    500    391      9  0.561   
4      5           Miami Dolphins     816    452    360      4  0.556   
5      6        Minnesota Vikings     886    478    397     11  0.546   
6      7         Baltimore Ravens     368    200    167      1  0.545   
7      8          New York Giants   1,321    692    596     33  0.536   
8      9           Denver Broncos     900    476    414     10  0.534   
9     10      San Francisco 49ers   1,018    532    472     14  0.529   

   First NFL Season    Division  
0               1960   NFC East  
1               1920  NFC North  
2               1921  NFC North  
3               1960   AFC East  
4               1966   AFC East  
5               1961  NFC North  
6               1996  AFC North  
7               1925   NFC East  
8               1960   AFC West  
9               1950   NFC West

In [36]:
df.rename(columns = lambda x: x.strip(), inplace=True)
df.columns

Index(['Rank', 'Team', 'GP', 'Won', 'Lost', 'Tied', 'Pct.', 'First NFL Season',
       'Division'],
      dtype='object')

In [37]:
df['Won'].mean()

534.6

In [76]:
# reindex df
df1 = DataFrame(
    np.random.randn(25).reshape(5,5),
    index=['a','b','c','d','e'],
    columns=['n1','n2','n3','n4','n5']
)
df2 = df1.reindex(['a','b','c','d','e','f'],
    fill_value = 0
)
df3 = df2.reindex(columns=['n1','n2','n3','n4','n5','n6'],
    fill_value = 0
)
df3


n1        n2        n3        n4        n5  n6
a  0.376539  0.069455  0.868086 -1.056898 -0.416001   0
b  0.311827 -0.574424 -2.173158  0.468213  0.625771   0
c  1.648488  0.346293  1.329515  0.125106  1.073953   0
d  1.531567 -1.433097  0.080672  0.027082 -0.809391   0
e  1.341430  0.411996 -0.313079 -0.530392 -2.029169   0
f  0.000000  0.000000  0.000000  0.000000  0.000000   0

In [4]:
df = DataFrame(
    np.random.randn(25).reshape(5,5),
    index=['a','b','c','d','e'],
    columns=['n1','n2','n3','n4','n5']
)

df

n1        n2        n3        n4        n5
a  0.670650  0.199397  0.140988 -0.274946  0.788798
b  0.154521 -0.054213 -1.891727 -1.238857 -1.615407
c  0.351410 -0.295638  0.538116  0.308322 -1.083437
d  0.117247  0.739685  0.409725  1.528958  0.338781
e  0.224334 -1.913016  0.480887 -0.738323 -0.011085

In [9]:
srs2 = Series([1,2,3,4,5], index=['a','b','c','d','e'])
srs2 # a b c d e # 1 2 3 4 5
srs2.values # array([ 1, 2, 3, 4, 5 ])
srs2.index # Int64Index([ 'a', 'b', 'c', 'd', 'e' ], dtype='object')
srs2['a'] # 1
srs2[0:3] # a b c d # 1 2 3 4
srs2[['a','b','c']] # a b c # 1 2 3
srs2[srs2 == 2] # b 2
srs2[(srs2>1) & (srs2<4)]
srs2[(srs2<2) | (srs2>4)] 

a    1
e    5
dtype: int64

In [4]:
df = DataFrame(
    np.arange(25).reshape(5,5),
    index=['a','b','c','d','e'],
    columns=['n1','n2','n3','n4','n5']
)
# select df
df['n1']
df[['n1','n2','n3']]
df[ (df['n3'] < 20) & (df['n3'] >5)]

n1  n2  n3  n4  n5
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19

In [10]:
srs1 = Series([1,2,3,4,5], index=['n1','n2','n3','n4','n5'])
df1 = DataFrame(
    np.arange(1,26,1).reshape(5,5),
    index=['a','b','c','d','e'],
    columns=['n1','n2','n3','n4','n5']
)
df1 + srs1 # srs1 will be added to each row of df1


n1         n2         n3         n4         n5
count   5.000000   5.000000   5.000000   5.000000   5.000000
mean   10.000000  11.000000  12.000000  13.000000  14.000000
std     7.905694   7.905694   7.905694   7.905694   7.905694
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     5.000000   6.000000   7.000000   8.000000   9.000000
50%    10.000000  11.000000  12.000000  13.000000  14.000000
75%    15.000000  16.000000  17.000000  18.000000  19.000000
max    20.000000  21.000000  22.000000  23.000000  24.000000

In [14]:
df = DataFrame(
    np.arange(1,26,1).reshape(5,5),
    index=['a','b','c','d','e'],
    columns=['n1','n2','n3','n4','n5']
)
df.agg(['sum','min','max','mean','median','std','count'])
# df

n1         n2         n3         n4         n5
sum     55.000000  60.000000  65.000000  70.000000  75.000000
min      1.000000   2.000000   3.000000   4.000000   5.000000
max     21.000000  22.000000  23.000000  24.000000  25.000000
mean    11.000000  12.000000  13.000000  14.000000  15.000000
median  11.000000  12.000000  13.000000  14.000000  15.000000
std      7.905694   7.905694   7.905694   7.905694   7.905694
count    5.000000   5.000000   5.000000   5.000000   5.000000

In [11]:
srs = Series([1,2,3,4,5], index=['a','b','c','d','e'])
srs['c'] = np.nan

# srs[srs.notnull()] 
srs.dropna()

a    1.0
b    2.0
d    4.0
e    5.0
dtype: float64

In [12]:
df = DataFrame(
    np.arange(1,26,1).reshape(5,5),
    index=['a','b','c','d','e'],
    columns=['col1','col2','col3','col4','col5']
)
df.loc['b', 'col2'] = np.nan
df

col1  col2  col3  col4  col5
a     1   2.0     3     4     5
b     6   NaN     8     9    10
c    11  12.0    13    14    15
d    16  17.0    18    19    20
e    21  22.0    23    24    25

In [5]:
srs = Series(np.arange(6),
    index = [[1,1,1,2,2,2],['a','b','c','a','b','c']]
) # 1a 1b 1c 2a 2b 2c
srs[1] # a b c # 0 1 2
srs[1]['a'] # 0


0

In [6]:
df = DataFrame(
    np.arange(1,17,1).reshape(4,4),
    index = [['a','a','b','b'],[1,2,1,2]],
    columns = [['A','A','B','B'],['i','ii','i','ii']]
)
df

A       B    
      i  ii   i  ii
a 1   1   2   3   4
  2   5   6   7   8
b 1   9  10  11  12
  2  13  14  15  16

In [17]:
# multi-level df
df = DataFrame(
    np.arange(1,17,1).reshape(4,4),
    index = [['a','a','b','b'],[1,2,1,2]],
    columns = [['A','A','B','B'],['i','ii','i','ii']]
)
# df.index.names = ['primary_i', 'secondary_i'] # name higher/lower indices
df.columns.names = ['primary_col', 'secondary_col']
# df.swaplevel() # swap inner-most row levels
# df.swaplevel(axis=1) # swap inner most column levels
# df.swaplevel('primary_i', 'secondary_i') # swap row levels by name

# df = df.sort_index(level=0) # sort by outer index
# df = df.sort_index(level=[0,1]) # primary sort by outer, secondary sort by inner

# df = df.sum(level = 'secondary_col') # sum by column level
df

primary_col     A       B    
secondary_col   i  ii   i  ii
a 1             1   2   3   4
  2             5   6   7   8
b 1             9  10  11  12
  2            13  14  15  16

In [29]:
df = DataFrame(
    np.arange(1,26,1).reshape(5,5),
    index=['a','b','c','d','e'],
    columns=['col1','col2','col3','col4','col5']
)
json = df.to_json('data.json', orient='split') # writes json file (split formatted)
df = pd.read_json('data.json', orient='split')
df

col1  col2  col3  col4  col5
a     1     2     3     4     5
b     6     7     8     9    10
c    11    12    13    14    15
d    16    17    18    19    20
e    21    22    23    24    25

In [24]:
df = pd.DataFrame.from_dict(
    {'row1': [0,1,2,3], 'row2': [4,5,6,7], 'row3': [8,9,10,11]},
    orient = 'index',
    columns = ['col1','col2','col3','col4']
)
df
dict = df.to_dict()
dict

{'col1': {'row1': 0, 'row2': 4, 'row3': 8},
 'col2': {'row1': 1, 'row2': 5, 'row3': 9},
 'col3': {'row1': 2, 'row2': 6, 'row3': 10},
 'col4': {'row1': 3, 'row2': 7, 'row3': 11}}

In [8]:
df = DataFrame(
    np.arange(1,26,1).reshape(5,5),
    index=['a','b','c','d','e'],
    columns=['col1','col2','col3','col4','col5']
)
xlsx = df.to_excel('data.xlsx', sheet_name='Sheet1')
df = pd.read_excel(
    'data.xlsx',
    index_col=0, # None -- no col provided, 0 -- use col index 0 as index
    header=0, # None -- no header provided, 0 -- use row index 0 as header
    sheet_name=0 # index -- 0, string -- 'Sheet1'
)
df

col1  col2  col3  col4  col5
a     1     2     3     4     5
b     6     7     8     9    10
c    11    12    13    14    15
d    16    17    18    19    20
e    21    22    23    24    25

In [11]:
df = DataFrame(
    np.arange(1,26,1).reshape(5,5),
    index=['a','b','c','d','e'],
    columns=['col1','col2','col3','col4','col5']
)
csv = df.to_csv('data.csv')
df = pd.read_csv('data.csv', index_col=0, header=0)
df

col1  col2  col3  col4  col5
a     1     2     3     4     5
b     6     7     8     9    10
c    11    12    13    14    15
d    16    17    18    19    20
e    21    22    23    24    25

In [16]:
df1 = pd.DataFrame.from_dict(
    {'row1': ['Landon',26], 'row2': ['Matt',25], 'row3': ['Brendan',42], 'row4': ['Andrew', 27]},
    orient = 'index',
    columns = ['Name','Age']
)
df2 = pd.DataFrame.from_dict(
    {'row1': ['Landon','Guitar'], 'row2': ['Matt','Karaoke'], 'row3': ['Brendan','Running'], 'row4': ['Andrew', 'Coding']},
    orient = 'index',
    columns = ['Name','Hobby']
)
df3 = df1.merge(
    df2,
    how='inner', # inner -- matches only, outer -- all, left -- all left rows, right -- all right rows
    on='Name', # merge on 'Name' col
)
df3 = pd.merge(
    df1,df2, # DFs to use
    on='Name', # merge on 'Name' col
    how='inner' # inner -- matches only, outer -- all, left -- all left rows, right -- all right rows
)
df3

Name  Age    Hobby
0   Landon   26   Guitar
1     Matt   25  Karaoke
2  Brendan   42  Running
3   Andrew   27   Coding

In [2]:
arr1 = np.arange(1,26,1).reshape(5,5)
arr2 = np.arange(26,51,1).reshape(5,5)

arr = np.concatenate([arr1,arr2], axis=0) # 5 cols, 10 rows
print(arr)
arr = np.concatenate([arr1,arr2], axis=1) # 10 cols, 5 rows
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
[[ 1  2  3  4  5 26 27 28 29 30]
 [ 6  7  8  9 10 31 32 33 34 35]
 [11 12 13 14 15 36 37 38 39 40]
 [16 17 18 19 20 41 42 43 44 45]
 [21 22 23 24 25 46 47 48 49 50]]


In [5]:
srs1 = Series([0,1,2], index=['a','b','c'])
srs2 = Series([4,5,6], index=['d','e','f'])
srs = pd.concat([srs1,srs2], axis=0)
srs

a    0
b    1
c    2
d    4
e    5
f    6
dtype: int64

In [12]:
df1 = DataFrame(
    np.arange(1,26,1).reshape(5,5),
    index=['a','b','c','d','e'],
    columns=['col1','col2','col3','col4','col5']
)
df2 = DataFrame(
    np.arange(26,51,1).reshape(5,5),
    index=['f','g','h','i','j'],
    columns=['col1','col2','col3','col4','col5']
)
df = pd.concat(
    [df1,df2],
    axis=0, # 0 -- add rows, 1 -- add cols
    ignore_index=False, # ignores old indicies, creates new ones
    join='outer' # outer -- use all col, inner -- only use shared col
)
df

col1  col2  col3  col4  col5
a     1     2     3     4     5
b     6     7     8     9    10
c    11    12    13    14    15
d    16    17    18    19    20
e    21    22    23    24    25
f    26    27    28    29    30
g    31    32    33    34    35
h    36    37    38    39    40
i    41    42    43    44    45
j    46    47    48    49    50

In [19]:
srs1 = Series([1,1,np.nan,1,1], index=['a','b','c','d','e'])
srs2 = Series([1,2,3,4,5], index=['a','b','c','d','e'])
srs1.combine_first(srs2) # combine, srs1 overrides srs2

a    1.0
b    1.0
c    3.0
d    1.0
e    1.0
dtype: float64

In [18]:
# combine df
df1 = DataFrame(
    [[1,1,np.nan],[1,np.nan,1],[1,1,np.nan]],
    index=['a','b','c',],
    columns=['col1','col2','col3']
)
df2 = DataFrame(
    [[1,2,3],[4,5,6],[7,8,9]],
    index=['a','b','d',],
    columns=['col1','col2','col3']
)
df = df1.combine_first(df2) # use values from df1, if NaN use value from df2
df

col1  col2  col3
a   1.0   1.0   3.0
b   1.0   5.0   1.0
c   1.0   1.0   NaN
d   7.0   8.0   9.0

In [30]:
df = DataFrame(
    np.arange(8).reshape(2,4), # 2 rows, 4 cols
    index=['a','b'],
    columns=['i','ii','iii','iv']
)
srs = df.stack() # single level -- returns multi-level series
df = srs.unstack() # back to single-level df
print(srs)
print(df)
df

a  i      0
   ii     1
   iii    2
   iv     3
b  i      4
   ii     5
   iii    6
   iv     7
dtype: int64
   i  ii  iii  iv
a  0   1    2   3
b  4   5    6   7


i  ii  iii  iv
a  0   1    2   3
b  4   5    6   7

In [33]:
srs1 = Series([1,2,3,4,5], index=['a','b','c','d','e'])
srs2 = Series([1,2,3,4,5], index=['a','b','c','d','e'])
srs = pd.concat([srs1,srs2],keys=['i','ii'])
df = srs.unstack()
print(srs)
print(df)
df

i   a    1
    b    2
    c    3
    d    4
    e    5
ii  a    1
    b    2
    c    3
    d    4
    e    5
dtype: int64
    a  b  c  d  e
i   1  2  3  4  5
ii  1  2  3  4  5


a  b  c  d  e
i   1  2  3  4  5
ii  1  2  3  4  5

In [35]:
# pivot 
df = pd.DataFrame.from_dict(
    {
        'row1': ['a',1,14],
        'row2': ['a',2,27],
        'row3': ['a',3,21],
        'row4': ['b',1,12],
        'row5': ['b',2,16],
        'row6': ['b',3,25],
        'row7': ['c',1,14],
        'row8': ['c',2,19],
        'row9': ['c',3,26],
    },
    orient = 'index',
    columns = ['col1','col2','col3']
)
df = df.pivot('col1','col2','col3') # rows, cols, vals
df

col2   1   2   3
col1            
a     14  27  21
b     12  16  25
c     14  19  26

In [43]:
# duplicates 
df = DataFrame({'col1':['a','a','a','b','b','b'], 'col2':[1,1,2,1,1,2]}) # 5 rows, 2 cols
df.duplicated() # duplicate ? true : false (returns series of booleans)
df[~df.duplicated()]

col1  col2
0    a     1
2    a     2
3    b     1
5    b     2

In [60]:
# applymap df
df = DataFrame(
    np.arange(1,26,1).reshape(5,5),
    index=['a','b','c','d','e'],
    columns=['col1','col2','col3','col4','col5']
)
df = df.applymap(lambda x : x**2)
df = df.applymap(lambda x : f'number: {x}')
df

col1         col2         col3         col4         col5
a    number: 1    number: 4    number: 9   number: 16   number: 25
b   number: 36   number: 49   number: 64   number: 81  number: 100
c  number: 121  number: 144  number: 169  number: 196  number: 225
d  number: 256  number: 289  number: 324  number: 361  number: 400
e  number: 441  number: 484  number: 529  number: 576  number: 625

In [61]:
df = DataFrame(
    np.arange(1,26,1).reshape(5,5),
    index=['a','b','c','d','e'],
    columns=['col1','col2','col3','col4','col5']
)
df['col1'] = df['col1'].map(lambda x : x**2)
df

col1  col2  col3  col4  col5
a     1     2     3     4     5
b    36     7     8     9    10
c   121    12    13    14    15
d   256    17    18    19    20
e   441    22    23    24    25

In [18]:
df = DataFrame(
    np.arange(1,13,1).reshape(3,4), # 3 rows, 4 cols
    index=[1,2,3],
    columns=[' col1         ','col2     a        ',' col3','col4']
)
df.index = df.index.map(lambda x: x + 1)
df.columns = df.columns.map(lambda x: x.replace('col','column')) # cols to uppercase
df.columns = df.columns.map(lambda x: x.upper())
df.columns = df.columns.map(lambda x: x.strip('A ')) # strip whitespace

df

COLUMN1  COLUMN2  COLUMN3  COLUMN4
2        1        2        3        4
3        5        6        7        8
4        9       10       11       12

In [3]:
df = DataFrame(
    np.arange(1,13,1).reshape(3,4), # 3 rows, 4 cols
    index=[1,2,3],
    columns=[' col1',' col2',' col3',' col4']
)
df.rename( index=lambda x: x - 1, columns=lambda x : x.strip().capitalize() )

Col1  Col2  Col3  Col4
0     1     2     3     4
1     5     6     7     8
2     9    10    11    12

In [24]:
# binning (bin values into discrete intervals)
numbers = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
bins = [0,5,10,15,20]
nums_cat = pd.cut(
    numbers, # list
    3, # bins
    precision=0, # number of decimals (bins)
    labels=['small','medium','large']
)
nums_cat = pd.cut(
    numbers,
    bins
) # bin edges specified
nums_cat.categories # list of bins
nums_cat.value_counts() # series (index -- bins, values -- counts)




(0, 5]      5
(5, 10]     5
(10, 15]    5
(15, 20]    5
dtype: int64

In [59]:
# outliers
np.random.seed(12345)
df = DataFrame(np.random.randn(5,4)) # 5 rows, 4 cols
df.describe() # returns df (each col -- count, mean, std, min, %, max)

col1 = df[0]
col1[np.abs(col1)>1] # find all values in df[0] where df[0] > 1 (abs val)

df[ np.abs(df[0]) > 1 ] # return df (all rows where df[0] > 1 (abs val)

0         1         2         3
1  1.965781  1.393406  0.092908  0.281746
4 -2.001637 -0.371843  1.669025 -0.438570

In [60]:
# return rows with null values
np.random.seed(12345)
df = DataFrame(np.random.randn(5,4)) # 5 rows, 4 cols
df.loc[0,2] = np.nan
df[ df.isnull().any(1) ] # return df (any row where elem == NaN)

0         1   2        3
0 -0.204708  0.478943 NaN -0.55573

In [4]:
df = DataFrame(
    np.arange(1,26,1).reshape(5,5),
    index=[0,1,2,3,4],
    columns=['col1','col2','col3','col4','col5']
)
df = df.take(np.random.permutation(5)) # shuffle indices
df

col1  col2  col3  col4  col5
1     6     7     8     9    10
3    16    17    18    19    20
2    11    12    13    14    15
4    21    22    23    24    25
0     1     2     3     4     5

In [20]:
# groupby df
df = DataFrame({
    'col1': ['a','b','c','b','a'],
    'col2': ['i','ii','ii','iii','iii'],
    'col3': ['A','C','B','C','A'],
    'col4': [1,2,3,1,1],
    'col5': [2,4,6,8,10]
})
group_obj1 = df['col4'].groupby(df['col2']) # SeriesGroupBy object
group_obj1.mean() # i ii iii # 1 2.5 1 (series)

group_obj2 = df.groupby('col1') # SeriesGroupBy object
group_obj2.mean() # returns df -- index (col1), cols (col4, col5), values (mean)
group_obj2.size() # returns series -- index (groups), values (counts)

group_obj3 = df.groupby(['col1','col2']) # SeriesGroupBy object
group_obj3.mean() # returns df -- multi-level index, cols (col4, col5), values (mean)

# for group_name, group_rows in group_obj2:
#     print(f"group: {group_name}")
#     print(group_rows)
#     print('\n')

# for (col1,col2), group_rows in group_obj3:
#     print(f'col1: {col1}, col2: {col2}')
#     print(group_rows)
#     print('\n')

# group_dict = dict(list(group_obj2))
# group_dict['a']


col4  col5
col1 col2            
a    i        1     2
     iii      1    10
b    ii       2     4
     iii      1     8
c    ii       3     6

In [11]:
df = DataFrame({
    'int1': [1,2,3,1,1],
    'int2': [2,4,6,8,10],
    'float1': [1.2,2.3,3.15,1.56,1.33],
    'float2': [2.76,4.44,6.57,8.5,10.11]
})
categories = {'int1':'int','int2':'int','float1':'float','float2':'float'}
categories = Series(
    ['int','int','float','float'],
    index=['int1','int2','float1','float2']
)

group_obj = df.groupby(categories,axis=1) # SeriesGroupBy object
sums = group_obj.sum()
sums

float   int
0   3.96   3.0
1   6.74   6.0
2   9.72   9.0
3  10.06   9.0
4  11.44  11.0

In [35]:
# multi-index df
cols = pd.MultiIndex.from_arrays(
    [['a','a','a','b','b'],[1,2,3,1,2]],
    names=['col','sub_col']
)
df = DataFrame(
    np.arange(1,26,1).reshape(5,5),
    columns=cols
)
group_obj = df.groupby(level=0,axis=1)
sums = group_obj.sum()
sums

col   a   b
0     6   9
1    21  19
2    36  29
3    51  39
4    66  49

In [31]:
# aggregations by column
df = DataFrame(
    np.arange(1,26,1).reshape(5,5),
    index=['a','b','c','d','e'],
    columns=['col1','col2','col3','col4','col5']
)
df['col1'].mean()
df[['col1','col2']].mean()

col1    11.0
col2    12.0
dtype: float64

In [16]:
# split, apply, combine (apply -- apply function along axis)
df = DataFrame({
    'wine': ['a','a','a','b','b','c','c','c'],
    'quality': [7,8,10,8,5,9,7,6],
    'percent_alc': [4.5,6,12,3.75,7,9,10,5]
})
df.sort_values('percent_alc',ascending=False,inplace=True)
def ranker(df):
    df['alc_content_rank'] = np.arange(len(df)) + 1
    return df
df = df.groupby('wine').apply(ranker)
df = df.sort_values('wine')
df

wine  quality  percent_alc  alc_content_rank
2    a       10        12.00                 1
1    a        8         6.00                 2
0    a        7         4.50                 3
4    b        5         7.00                 1
3    b        8         3.75                 2
6    c        7        10.00                 1
5    c        9         9.00                 2
7    c        6         5.00                 3

In [26]:
# io.StringIO
from io import StringIO
data = '''\
id,animal,intelligence
1,dog,smart
2,dog,smart
3,cat,dumb
4,cat,dumb
5,dog,dumb
6,cat,smart
'''
df = pd.read_csv(StringIO(data))

# cross tabulation (frequency counter)
pd.crosstab(df['animal'],df['intelligence'], margins=True)

intelligence  dumb  smart  All
animal                        
cat              2      1    3
dog              1      2    3
All              3      3    6